# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - productbootcamp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d16e4ccb9e574583b12ab32e881fc13d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5bec81ed4c6f4ddebdb7443159050e2a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d16e4ccb9e574583b12ab32e881fc13d }}/jhctdev/product-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'productbootcamp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_71007aae9082464ea35d8a722cb71301 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d16e4ccb9e574583b12ab32e881fc13d }}/jhctdev/product-service:${{ github.sha }}'